server:
  port: 8088
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ForumSystem
    username: postgres
    password: 123456

logging:
  level:
    org.apache.ibatis: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
springdoc:
  show-actuator: true
  swagger-ui:
  path: /swagger-ui.html

